#' Synthetic example methylation dataset for the commaKit package
#'
#' A \code{\link{commaData}} object built from simulated Oxford Nanopore
#' methylation data. This dataset is used in package examples, vignettes, and
#' tests. It does not represent real biological data.
#'
#' @format A \code{commaData} object with:
#' \describe{
#'   \item{\strong{Sites}}{588 methylation sites (393 6mA GATC sites and
#'     195 5mC CCWGG sites) on a simulated 100 kb chromosome
#'     (\code{"chr_sim"}).}
#'   \item{\strong{Samples}}{6 samples: \code{ctrl_1}, \code{ctrl_2},
#'     \code{ctrl_3} (condition \code{"control"}) and \code{treat_1},
#'     \code{treat_2}, \code{treat_3} (condition \code{"treatment"}).}
#'   \item{\strong{Assays}}{
#'     \describe{
#'       \item{\code{methylation}}{Beta values (proportion methylated reads,
#'         0–1). \code{NA} where coverage < 5.}
#'       \item{\code{coverage}}{Integer read depth (10–150 per site).}
#'       \item{\code{mod_counts}}{Integer modified-read counts reconstructed
#'         from the simulated beta and coverage values.}
#'       \item{\code{canonical_counts}}{Integer canonical-read counts
#'         reconstructed from the simulated beta and coverage values.}
#'     }
#'   }
#'   \item{\strong{rowRanges}}{GRanges with 1-bp ranges per site. mcols include
#'     \code{mod_type}, \code{motif}, \code{mod_context}, and \code{is_diff}
#'     (ground-truth differential methylation status for testing).}
#'   \item{\strong{colData}}{Per-sample metadata: \code{sample_name},
#'     \code{condition}, \code{replicate}, \code{caller}.}
#'   \item{\strong{Seqinfo}}{Chromosome sizes: \code{c(chr_sim = 100000L)}.}
#'   \item{\strong{annotation}}{5 simulated genomic features (genes, rRNA, tRNA).}
#'   \item{\strong{motifSites}}{Empty \code{GRanges} (no motif search was run).}
#' }
#'
#' @details
#' The dataset simulates an experiment where 30 of the 393 6mA GATC sites are
#' differentially methylated between control and treatment conditions. Control
#' samples have high methylation at these sites (~0.9 beta), while the
#' treatment samples have low methylation (~0.25 beta). This ground truth is
#' stored in \code{rowData(comma_example_data)$is_diff} for use in testing
#' \code{diffMethyl()} (implemented in Phase 4).
#'
#' 5mC CCWGG sites are not differentially methylated and serve to test multi-
#' modification-type functionality.
#'
#' The dataset was generated by \code{data-raw/create_example_data.R} using
#' \code{set.seed(1312)}.
#'
#' @examples
#' data(comma_example_data)
#' comma_example_data
#' modTypes(comma_example_data)
#' motifs(comma_example_data)
#' sampleInfo(comma_example_data)
#' dim(methylation(comma_example_data))
#'
#' @return A \code{\link{commaData}} object (see Details and Format sections
#'   above for structure).
#'
#' @source Simulated data generated by \code{data-raw/create_example_data.R}
#'
#' @name comma_example_data
#' @docType data
#' @keywords datasets
NULL
