# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown-deploy:
    name: pkgdown deploy
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-deploy
      cancel-in-progress: true
    container: bioconductor/bioconductor_docker:RELEASE_3_22@sha256:e34177896c1579f66d48b756e4229b58237499183a089da084af72d7aba1d40a
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_AUTOLOADER_ENABLED: "FALSE"
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Check R and Bioconductor versions
        run: |
          Rscript -e 'cat("R ", as.character(getRversion()), "\n", sep = "")'
          Rscript -e 'cat("Bioconductor ", as.character(BiocManager::version()), "\n", sep = "")'

      - name: Install deploy system tools
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends rsync

      - uses: r-lib/actions/setup-r-dependencies@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          packages: any::sessioninfo
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: |
          pkgdown::build_site(new_process = FALSE, install = FALSE)
          file.create(file.path("docs/_site", ".nojekyll"))
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e # v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs/_site
