name: Source quality

on:
  push:
    branches: [main, master]
  pull_request:

permissions: read-all

jobs:
  source-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          r-version: "4.6.1"

      - uses: posit-dev/setup-air@cf390573ff4fe0f198f35df3a642b1409328d859 # v1
        with:
          version: "0.10.0"

      - name: Install lintr
        run: Rscript --vanilla -e 'install.packages("lintr")'

      - name: Check R formatting
        run: air format . --check

      - name: Lint package
        run: |
          Rscript --vanilla -e '
            lints <- lintr::lint_package()
            print(lints)
            if (length(lints) > 0L) quit(status = 1L)
          '
